project:
  type: website
  output-dir: docs

website:
  reader-mode: true
  page-footer: 
    left: "Created with [Quarto](https://quarto.org/) • [License](https://creativecommons.org/licenses/by-nc/4.0/)" 
    center: "Copyright © 2024 Victoria Sass <br> Course content adapted from [Kyle Crowder's](https://soc.washington.edu/people/kyle-crowder) Winter 2020 class"
    right: 
    - icon: envelope-at
      href: mailto:vsass@uw.edu
    - icon: google
      href: https://scholar.google.com/citations?user=A3lEdiIAAAAJ&hl=en
    - icon: github 
      href: https://github.com/vsass
    - icon: file-person
      href: http://vsass.github.io/Sass_Victoria_CV_2023.pdf
  navbar:
    search: true
    left:
      - text: "Home"
        url: "http://vsass.github.io"
      - text: "SOC 221"
        href: index.qmd
      - syllabus.qmd
      - text: "Lectures"
        menu: 
          - text: "Lecture 1:<br>Introductions; Overview of statistics; Producting data: surveys and sampling"
            href: Lectures/lecture1.qmd
          - text: "Lecture 2:<br>Frequency tables; Graphical techniques"
            href: Lectures/lecture2.qmd
          - text: "Lecture 3:<br>Measures of central tendency; Measures of variability"
            href: Lectures/lecture3.qmd
          - text: "Lecture 4:<br>Probability and probability distributions; Normal distributions"
            href: Lectures/lecture4.qmd
          - text: "Lecture 5:<br>Sampling distributions<br>Central limit theorem; Logic of inference"
            href: Lectures/lecture5.qmd
          - text: "Lecture 6:<br>Estimation: confidence intervals for means; Estimation: confidence intervals for proportions"
            href: Lectures/lecture6.qmd
          - text: "Lecture 7:<br>Hypothesis testing for one sample; Hypothesis testing for two samples"
            href: Lectures/lecture7.qmd
          - text: "Lecture 8:<br>Two-way tables and chi-square; Scatterplots and correlation"
            href: Lectures/lecture8.qmd
          - text: "Lecture 9:<br>Bivariate regression; Inference for regression"
            href: Lectures/lecture9.qmd
          - text: "Lecture 10:<br>Multivariate regression"
            href: Lectures/lecture10.qmd
      - text: "Homework"
        menu: 
          - text: "Homework 1"
            href: homework/homework1.qmd
          - text: "Homework 2"
            href: homework/homework2.qmd
          - text: "Homework 3"
            href: homework/homework3.qmd
          - text: "Homework 4"
            href: homework/homework4.qmd
          - text: "Homework 5"
            href: homework/homework5.qmd
          - text: "Homework 6"
            href: homework/homework6.qmd
          - text: "Homework 7"
            href: homework/homework7.qmd
        
format:
  html:
    highlight-style: a11y-dark
    link-external-newwindow: true
    theme: 
      - styles.scss
    grid: 
      sidebar-width: 300px
      body-width: 1000px
    fontsize: 1.1rem
    toc: false


# Scheduling variables
lectures:
  one: "17 June 2024"
  two: "24 June 2024"
  three: "26 June 2024"
  four: "1 July 2024"
  five: "3 July 2024"
  six: "8 July 2024"
  seven: "10 July 2024"
  eight: "15 July 2024"
  nine: "17 July 2024"
  ten: "22 July 2024"
  eleven: "24 July 2024"
  twelve: "29 July 2024"
  thirteen: "31 July 2024"
  fourteen: "5 August 2024"
  fifteen: "7 August 2024"