project:
  type: website
  output-dir: docs

website:
  reader-mode: true
  page-footer: 
    left: "Created with [Quarto](https://quarto.org/) • [License](https://creativecommons.org/licenses/by-nc/4.0/)" 
    center: "Copyright © 2023 Victoria Sass <br> Course content adapted from [Kyle Crowder's](https://soc.washington.edu/people/kyle-crowder) Winter 2020 class"
    right: 
    - icon: envelope-at
      href: mailto:vsass@uw.edu
    - icon: google
      href: https://scholar.google.com/citations?user=A3lEdiIAAAAJ&hl=en
    - icon: github 
      href: https://github.com/vsass
    - icon: file-person
      href: http://vsass.github.io/Sass_Victoria_CV_2023.pdf
  navbar:
    search: true
    left:
      - text: "Home"
        url: "http://vsass.github.io"
      - text: "SOC 221"
        href: index.qmd
      - syllabus.qmd
      - text: "Lectures"
        file: Lectures/lectures.qmd
      - text: "Homework"
        file: Homework/homework.qmd
  sidebar: 
    - title: "Lectures"
      style: "docked"
      contents: 
        - Lectures/lectures.qmd
        - Lectures/Lecture1/CSSS508_Lecture1_index.qmd
        - Lectures/Lecture2/CSSS508_Lecture2_index.qmd
        - Lectures/Lecture3/CSSS508_Lecture3_index.qmd
        - Lectures/Lecture4/CSSS508_Lecture4_index.qmd
        - Lectures/Lecture5/CSSS508_Lecture5_index.qmd
        - Lectures/Lecture6/CSSS508_Lecture6_index.qmd
        - Lectures/Lecture7/CSSS508_Lecture7_index.qmd
        - Lectures/Lecture8/CSSS508_Lecture8_index.qmd
        - Lectures/Lecture9/CSSS508_Lecture9_index.qmd
        - Lectures/Lecture10/CSSS508_Lecture10_index.qmd
        - Lectures/Lecture11/CSSS508_Lecture11_index.qmd
        - Lectures/Lecture12/CSSS508_Lecture12_index.qmd
        - Lectures/Lecture13/CSSS508_Lecture13_index.qmd
        - Lectures/Lecture14/CSSS508_Lecture14_index.qmd

    - title: "Homework"
      contents: 
        - Homework/homework.qmd
        - Homework/HW1/homework1.qmd
        - Homework/HW2/homework2.qmd
        - Homework/HW3/homework3.qmd
        - Homework/HW4/homework4.qmd
        - Homework/HW5/homework5.qmd
        - Homework/HW6/homework6.qmd
        - Homework/HW7/homework7.qmd
        - Homework/HW8/homework8.qmd

format:
  html:
    highlight-style: a11y-dark
    link-external-newwindow: true
    theme: 
      - styles.scss
    grid: 
      sidebar-width: 300px
      body-width: 1000px
    fontsize: 1.1rem
    toc: false


